/**
 * Train the Header Classifier Model
 *
 * This script uses the training data generated by trainingDataGenerator.js
 * to train the HeaderClassifier model.
 */

const fs = require("fs");
const path = require("path");
const { SimpleHeaderClassifier } = require("./simpleHeaderClassifier");
const { generateTrainingData } = require("./trainingDataGenerator");

const TRAINING_DIR = path.join(__dirname, "../data/training");
const MODEL_DIR = path.join(__dirname, "../models");
const MODEL_PATH = path.join(MODEL_DIR, "header_classifier.json");

async function trainModel() {
  try {
    // Create model directory if it doesn't exist
    if (!fs.existsSync(MODEL_DIR)) {
      fs.mkdirSync(MODEL_DIR, { recursive: true });
    }

    // Generate training data if needed
    const trainingDataPath = path.join(
      TRAINING_DIR,
      "header_training_data.json"
    );
    if (!fs.existsSync(trainingDataPath)) {
      // console.log("Generating training data...");
      await generateTrainingData();
    }

    // Load training data
    // console.log("Loading training data...");
    const allTrainingData = JSON.parse(fs.readFileSync(trainingDataPath));

    // Use a subset for faster training (first 500 examples)
    const trainingData = allTrainingData.slice(0, 500);
    // console.log(
    //   `Using ${trainingData.length} examples out of ${allTrainingData.length} total`
    // );

    // Initialize and train the classifier
    // console.log("Training classifier...");
    const classifier = new SimpleHeaderClassifier();
    classifier.train(trainingData);

    // Save the trained model
    // console.log("Saving model...");
    classifier.save(MODEL_PATH);

    // console.log(`Model trained and saved to ${MODEL_PATH}`);
    // console.log(`Processed ${trainingData.length} examples`);

    // Test the model on a few examples
    // console.log("\nTesting model on some examples:");
    const testExamples = [
      { text: "EDUCATION", index: 10, total: 100 },
      { text: "WORK EXPERIENCE", index: 30, total: 100 },
      { text: "Some random text in a paragraph.", index: 50, total: 100 },
      { text: "PUBLICATIONS", index: 70, total: 100 },
      { text: "324782830.54", index: 704, total: 100 },
      { text: "Kietye", index: 750, total: 100 },
      { text: "Kietye123", index: 7043, total: 100 },
      { text: "Atricles", index: 7543, total: 100 },
      { text: "Articles", index: 443, total: 100 },
      // Add more test cases below:
      { text: "Peer-reviewed Publications", index: 100, total: 100 },
      { text: "White House Reports", index: 200, total: 1000 },
      { text: "19%.)", index: 300, total: 1000 },
      { text: "2020.", index: 400, total: 1000 },
      { text: "PATENTS", index: 500, total: 1000 },
      {
        text: "Workshop Papers and Technical Reports",
        index: 600,
        total: 1000,
      },
      { text: "4, 2024.", index: 700, total: 1000 },
      {
        text: "Policy-related Publications and Reports",
        index: 800,
        total: 1000,
      },
      { text: "Book Reviews", index: 900, total: 1000 },
      { text: "Thesis", index: 950, total: 1000 },
      { text: "Some random number: 1412.3756", index: 999, total: 1000 },
      { text: "EXPERIENCE", index: 20, total: 100 },
      { text: "Research Experience", index: 21, total: 100 },
      { text: "Professional Experience", index: 22, total: 100 },
      { text: "Conference Presentations", index: 23, total: 100 },
      { text: "SELECTED PUBLICATIONS", index: 24, total: 100 },
      { text: "Published Works", index: 25, total: 100 },
      { text: "Scholarly Publications", index: 26, total: 100 },
      { text: "Journal Articles", index: 27, total: 100 },
      { text: "Book Chapters", index: 28, total: 100 },
      { text: "Book Reviews", index: 29, total: 100 },
      { text: "Invited Publications", index: 30, total: 100 },
      { text: "Works in Progress", index: 31, total: 100 },
      { text: "Recent Publications", index: 32, total: 100 },
      { text: "Refereed Publications", index: 33, total: 100 },
      { text: "Conference Proceedings", index: 34, total: 100 },
      { text: "Published Abstracts", index: 35, total: 100 },
      { text: "PATENTS", index: 36, total: 100 },
      { text: "Thesis", index: 37, total: 100 },
      {
        text: "Some random sentence with numbers 2023.",
        index: 38,
        total: 100,
      },
      { text: "1. Introduction", index: 39, total: 100 },
      { text: "[M5] Some publication entry", index: 40, total: 100 },
      { text: "4, 2024.", index: 41, total: 100 },
      { text: "19%.)", index: 42, total: 100 },
      { text: "1412.3756", index: 43, total: 100 },
      { text: "2020.", index: 44, total: 100 },
      { text: "2017.", index: 45, total: 100 },
      { text: "2021.", index: 46, total: 100 },
      { text: "2013.", index: 47, total: 100 },
      { text: "Some completely unrelated line.", index: 48, total: 100 },
      { text: "Another random line.", index: 49, total: 100 },
      { text: "ais jdgl;kaj  s;ldkfja l;sdkjf", index: 345, total: 100 },
    ];

    testExamples.forEach((example) => {
      const isHeader = classifier.predict(
        example.text,
        example.index,
        example.total
      );
      console.log(`"${example.text}": ${isHeader ? "Header" : "Not Header"}`);
    });
  } catch (error) {
    console.error("Error training model:", error);
  }
}

if (require.main === module) {
  trainModel().catch(console.error);
}

module.exports = { trainModel };
